name: 提出内容の確認
on:
  - push

jobs:
  ex1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
      - name: ex1 check
        run: |
          cd ex1
          egrep "世界よこんにちは" Hello.txt
  ex2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
      - uses: actions/setup-python@v4
        with:
          cache: "pipenv"
      - name: setup pipenv
        run: |
          sudo apt-get update
          sudo apt-get install -y pipenv
          cd ex2
          pipenv install --dev
      - name: ex2 check
        run: |
          cd ex2
          pipenv run pytest
      
