name: 提出内容の確認
on:
  - push

jobs:
  ex1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
      - name: ex1 check
        run: |
          cd ex1
          egrep "世界よこんにちは" Hello.txt
      - uses: actions/setup-python@v4
        with:
          cache: "pipenv"
      - name: Run image
        uses: tiagovrtr/actions-pipenv@v1
      - name: ex2 check
        run: |
          cd ex2
          pipenv run pytest
      
